### ISSUE TITLE
Twitter ways of authentication defined in timeline yaml not working.

### ISSUE THREAD

**Issue by bharat15-ml** [scholzj/build-your-own-social-media-analytics-with-apache-kafka#2]
Hello @scholzj , I also tried running this demo, and facing an issue while creating a connector using 10-timeline.yaml.

Even though the connector twitter-timeline was created successfully, while observing connect pod logs, it seems that twitter authentication not working as expected. I tried to search and figure out the issue with Twitter authentication possible way but got a bit confused with following their developer docs for possible authentication and changes they made in the new API.

I found these error logs in connect pods - 

    TwitterException{exceptionCode=[62590fa6-0b06ac7d], statusCode=403, message=You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (eg. media post, oauth) only. If you need access to this endpoint, you may try a different access level.}

Could you pls help me with relevant changes if needed to create a connector So that Twitter authentication works? Thanks!!

**Comment by scholzj** [comment]
There have been many changes to Twitter APIs, what access are you allowed etc. since the new ownership and I haven't run the demo since. You would have to deal with it on your own I'm afraid.
